# Generated by Django 4.2.6 on 2023-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('message_details', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=70)),
                ('from_name', models.CharField(max_length=50)),
                ('replied_message_id', models.IntegerField()),
                ('replied_message_details', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('content', models.TextField()),
                ('joined', models.BooleanField()),
            ],
        ),
    ]
