# Generated by Django 4.2.6 on 2023-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tg_channel_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=70)),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tg_group_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=70)),
                ('message_details', models.CharField(max_length=50)),
                ('message_id', models.IntegerField()),
                ('replied_message_details', models.CharField(max_length=50)),
                ('replied_message_id', models.IntegerField()),
                ('joined', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parser_content',
        ),
    ]
