# Generated by Django 4.2.6 on 2023-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=70)),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='group_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, max_length=70, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=70)),
                ('message_details', models.CharField(max_length=50)),
                ('message_id', models.IntegerField()),
                ('replied_message_details', models.CharField(max_length=50)),
                ('replied_message_id', models.IntegerField()),
                ('joined', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='group_video_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_from_learning', models.TextField(blank=True, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_duration', models.CharField(blank=True, max_length=70, null=True)),
                ('data_title', models.CharField(max_length=70)),
                ('message_details', models.CharField(max_length=50)),
                ('message_id', models.IntegerField()),
                ('replied_message_details', models.CharField(max_length=50)),
                ('replied_id', models.IntegerField()),
                ('from_name', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
